[installed]
client_id = "541182294198-cl82q87l43344bvn2sqc3903r9f31f82.apps.googleusercontent.com"
client_secret = "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"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
redirect_uris = ["https://mv-gsc-connector.streamlit.app/", "http://localhost:8501/"]
